command_timeout = 10000

format = """
$hostname$directory$git_branch$git_status$env_var$status$cmd_duration
$character
"""

[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = 'bold green'

[directory]
truncation_length = 3
truncate_to_repo = true
style = 'cyan'
format = ':/[$path]($style) '

[git_branch]
symbol = 'î‚ '
style = 'purple'
format = '[$symbol$branch]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]](red) )'
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
staged = "âœš"
modified = "âš "
untracked = "?"
stashed = "ğŸ“¦"
deleted = "âœ˜"
conflicted = "âš”"

[env_var.K8S_INFO]
format = '[âˆ$env_value](bold blue) '
default = 'âˆ no-cluster'

[status]
style = 'bold red'
symbol = 'âœ—'
format = ' [$symbol $status]($style)'
disabled = false

[cmd_duration]
min_time = 2000  # show if command took > 2 seconds
format = 'â± [$duration]($style)'
style = 'bold yellow'

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
